dir=/home/runner/aria2c_downloads
file-allocation=trunc
max-connection-per-server=32
split=32
min-split-size=10M
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=0
max-upload-limit=0
max-concurrent-downloads=30
continue=true
timeout=30
retry-wait=5
max-tries=5
enable-rpc=true
rpc-listen-port=6800
rpc-allow-origin-all=true
rpc-listen-all=true
bt-enable-lpd=false
bt-seed-unverified=false
seed-time=0
bt-max-peers=55
bt-save-metadata=true
follow-torrent=mem
bt-remove-unselected-file=true
auto-file-renaming=false
allow-overwrite=true
conditional-get=true
http-accept-gzip=true
uri-selector=adaptive
lowest-speed-limit=0
