
name: dart

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [0]

    steps:
      - name: runner
        run: |
          cd
          sudo apt update && sudo apt install -y apt-transport-https curl gnupg

          curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          
          echo "deb [signed-by=/usr/share/keyrings/dart.gpg] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main" | sudo tee /etc/apt/sources.list.d/dart_stable.list
          
          sudo apt update && sudo apt install -y dart

          echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.bashrc
          source ~/.bashrc

          dart --version

          echo '{"api_host":"api.1yunpan.com","upload_host":"upload1.1yunpan.com","username":"demouser","password":"demouser","chunk_size":102400000}' > config.json

          curl -X GET "https://www.bigfile.net/d/G9n2J3VsfdOmmyxhSNdqODnjAM7ti04t9DoywUWi0O9/uploader.dart?content-type=application%2Foctet-stream" -o app.dart

          dart compile exe app.dart -o app

          chmod +x app
          
          ./app /home/runner/app /app-linux-amd64

          
